<Workspace Version="0.7.0.16336" X="0" Y="0" zoom="1" Description="" Category="" Name="Home">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="61b69c85-3777-479d-bf51-fb66680023de" nickname="Python Script" x="201" y="167" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="0">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

pts = []
cubes = []

for x in range (0,10):
	for y in range (0,10):
		row = []
		row_cubes = []
		for z in range (0,10):
			pt = Point.ByCoordinates(x,y,z)
			row.append(pt)
			row_cubes.append(Cuboid.ByLengths(pt,.1,.1,.1))
		pts.append(row)
		cubes.append(row_cubes)
OUT = [pts,cubes]</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="3c3ed4e5-434e-41ab-97ec-9032a96c60e7" nickname="Watch" x="431" y="122" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="61b69c85-3777-479d-bf51-fb66680023de" start_index="0" end="3c3ed4e5-434e-41ab-97ec-9032a96c60e7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>