<?xml version="1.0" encoding="utf-8"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\bin\AnyCPU\Debug\DynamoTestFramework.dll" total="4" failures="0" not-run="0" date="2013-11-26" time="17:48:18" errors="2" inconclusive="0" ignored="0" skipped="0" invalid="0">
  <test-suite name="DynamoTestFrameworkTests" description="Unit tests in Revit." time="1.1691169" asserts="4" type="TestFixture" result="Success" executed="True">
    <results>
      <test-suite name="ProtoToRevitCurveTests" description="Unit tests in Revit." time="1.1691169" asserts="4" type="TestFixture" result="Success" executed="True">
        <results>
          <test-case name="BSplineCurve_Basic" success="False" time="0.280028" executed="True" asserts="0" result="Error">
            <failure>
              <message>System.Exception : BSplineCurve.ByControlVertices operation failed</message>
              <stack-trace>   at DSRevitNodesTests.GeometryConversion.ProtoToRevitCurveTests.BSplineCurve_Basic() in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodesTests\GeometryConversion\ProtoToRevitCurveTests.cs:line 69</stack-trace>
            </failure>
          </test-case>
          <test-case name="Circle_Basic" success="True" time="0.280028" executed="True" asserts="0" result="Success" />
          <test-case name="Arc_Basic" success="False" time="0.2750275" executed="True" asserts="0" result="Error">
            <failure>
              <message>System.Exception : Arc.ByCenterPointRadiusAngle operation failed</message>
              <stack-trace>   at Autodesk.DesignScript.Geometry.Arc.ByCenterPointRadiusAngleCore(Point centerPoint, Double radius, Double startAngle, Double sweepAngle, Vector&amp; normal)
   at Autodesk.DesignScript.Geometry.Arc..ctor(Point centerPoint, Double radius, Double startAngle, Double sweepAngle, Vector normal, Boolean persist)
   at Autodesk.DesignScript.Geometry.Arc.ByCenterPointRadiusAngle(Point centerPoint, Double radius, Double startAngle, Double sweepAngle, Vector normal)
   at DSRevitNodesTests.GeometryConversion.ProtoToRevitCurveTests.Arc_Basic() in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodesTests\GeometryConversion\ProtoToRevitCurveTests.cs:line 111</stack-trace>
            </failure>
          </test-case>
          <test-case name="Line_Basic" success="True" time="0.3340334" executed="True" asserts="4" result="Success" />
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>